services:
  php:
    container_name: lab6-php
    restart: 'no'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: 1000
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./data
        target: /var/db/app
